#!/bin/bash

Github=/home/pc/Dokumenti/GitHub/SloHenoh

rm slohenoh_work.xml
rm enghenoh_work.xml

cp sloenghenoh.xml slohenoh_work.xml

#===================================
echo "   Najprej naredimo SLO verzijo"

# Uporabil sem ukaz paste, da sem zdruzil 
# Poisce vse vrstice, ki se zacnejo z ENG in jih izbrise, pusti vse ostalo."
sed -i '/^ENG/d' slohenoh_work.xml

# Pobrise prve stiri znake na zacetku vrstic - da se znebi SLO
sed -i 's/^....//' slohenoh_work.xml

# Pozenimo SED za opombe  <opomba>(     ->    <note type="x-footnote">
sed -i "s/<opomba>(/<note type=\"x-footnote\">/g" slohenoh_work.xml
#                         </opomba>     ->     </note>
sed -i "s/)<\/opomba>/<\/note>/g" slohenoh_work.xml

# Reference je trebe drugace prikazati
#   Zamenja       ^<r r=   z   ^<note type="crossReference"^>^<reference osisRef=
sed -i "s/<r r=/<note type=\"crossReference\"><reference osisRef=/g" slohenoh_work.xml
#   Zamenja       ^</r^>   z      ^</reference^>^</note^>
sed -i "s/<\/r>/<\/reference><\/note>/g" slohenoh_work.xml

#   Zamenja opomba z transChange type= added 
#    Zamenja       ^<dodano^>[   z   ^<transChange type="added"^>[
sed -i "s/<dodano>\[/<transChange type=\"added\">[/g" slohenoh_work.xml
#                 ]^</dodano^>  z   ]^<\/transChange^>^<\/seg^>
sed -i "s/\]<\/dodano>/\]<\/transChange>/g" slohenoh_work.xml


# Pobrise prazne vrstice
sed -i "/^$/d" slohenoh_work.xml

mkdir mods.d                               > /dev/null 2>&1
mkdir modules                              > /dev/null 2>&1
mkdir modules/genbook                      > /dev/null 2>&1
mkdir modules/genbook/rawgenbook           > /dev/null 2>&1
mkdir modules/genbook/rawgenbook/slohenoh  > /dev/null 2>&1

echo  "   Preveri XML"
/usr/bin/xmllint --noout --schema http://www.crosswire.org/~dmsmith/osis/osisCore.2.1.1-cw-latest.xsd slohenoh_work.xml

sleep 2  # Waits 2 seconds.

# Konvertireanje v SWORD modul
/usr/bin/xml2gbs -fO slohenoh_work.xml slohenoh > /dev/null 2>&1
mv slohenoh.bdt modules/genbook/rawgenbook/slohenoh/
mv slohenoh.dat modules/genbook/rawgenbook/slohenoh/
mv slohenoh.idx modules/genbook/rawgenbook/slohenoh/
cp -u slohenoh.conf mods.d/

# Preverimo ali je sed pravilno naredil
cat slohenoh_work.xml |grep opomba\>
cat slohenoh_work.xml |grep "ENG "


cp sloenghenoh.xml enghenoh_work.xml

#===================================
echo "   Sedaj naredimo ENG verzijo"

# Poisce vse vrstice, ki se zacnejo z ENG in jih izbrise, pusti vse ostalo."
sed -i '/^SLO/d' enghenoh_work.xml

# Pobrise prve stiri znake na zacetku vrstic - da se znebi ENG
sed -i 's/^....//' enghenoh_work.xml

# Pozenimo SED za opombe  <opomba>(     ->    <note type="x-footnote">
sed -i "s/<opomba>(/<note type=\"x-footnote\">/g" enghenoh_work.xml
#                         </opomba>     ->     </note>
sed -i "s/)<\/opomba>/<\/note>/g" enghenoh_work.xml


# Reference je trebe drugace prikazati
#   Zamenja       ^<r r=   z   ^<note type="crossReference"^>^<reference osisRef=
sed -i "s/<r r=/<note type=\"crossReference\"><reference osisRef=/g" enghenoh_work.xml
#   Zamenja       ^</r^>   z      ^</reference^>^</note^>
sed -i "s/<\/r>/<\/reference><\/note>/g" enghenoh_work.xml

#   Zamenja opomba z transChange type= added 
#    Zamenja       ^<dodano^>[   z   ^<transChange type="added"^>[
sed -i "s/<dodano>\[/<transChange type=\"added\">[/g" enghenoh_work.xml
#                 ]^</dodano^>  z   ]^<\/transChange^>^<\/seg^>
sed -i "s/\]<\/dodano>/\]<\/transChange>/g" enghenoh_work.xml

#   Zamenja slovenska imena knjig v angleska v angleskem fajlu
sed -i 's/\">\[1 Jn/\">\[1John/g'   enghenoh_work.xml
sed -i 's/\">\[1 Kor/\">\[1Cor/g'   enghenoh_work.xml
sed -i 's/\">\[1 Kr/\">\[1Kgs/g'    enghenoh_work.xml
sed -i 's/\">\[1 Krn/\">\[1Chr/g'   enghenoh_work.xml
sed -i 's/\">\[1 Mz/\">\[Gen/g'     enghenoh_work.xml
sed -i 's/\">\[1 Pt/\">\[1Pet/g'    enghenoh_work.xml
sed -i 's/\">\[1 Sam/\">\[1Sam/g'   enghenoh_work.xml
sed -i 's/\">\[1 Tes/\">\[1Thess/g' enghenoh_work.xml
sed -i 's/\">\[1 Tim/\">\[1Tim/g'   enghenoh_work.xml
sed -i 's/\">\[2 Jn/\">\[2John/g'   enghenoh_work.xml
sed -i 's/\">\[2 Kor/\">\[2Cor/g'   enghenoh_work.xml
sed -i 's/\">\[2 Kr/\">\[2Kgs/g'    enghenoh_work.xml
sed -i 's/\">\[2 Krn/\">\[2Chr/g'   enghenoh_work.xml
sed -i 's/\">\[2 Mz/\">\[Exod/g'    enghenoh_work.xml
sed -i 's/\">\[2 Pt/\">\[2Pet/g'    enghenoh_work.xml
sed -i 's/\">\[2 Sam/\">\[2Sam/g'   enghenoh_work.xml
sed -i 's/\">\[2 Tes/\">\[2Thess/g' enghenoh_work.xml
sed -i 's/\">\[2 Tim/\">\[2Tim/g'   enghenoh_work.xml
sed -i 's/\">\[3 Jn/\">\[3John/g'   enghenoh_work.xml
sed -i 's/\">\[3 Mz/\">\[Lev/g'     enghenoh_work.xml
sed -i 's/\">\[4 Mz/\">\[Num/g'     enghenoh_work.xml
sed -i 's/\">\[5 Mz/\">\[Deut/g'    enghenoh_work.xml
sed -i 's/\">\[Abd/\">\[Obad/g'     enghenoh_work.xml
sed -i 's/\">\[Ag/\">\[Hag/g'       enghenoh_work.xml
sed -i 's/\">\[Am/\">\[Amos/g'      enghenoh_work.xml
sed -i 's/\">\[Apd/\">\[Acts/g'     enghenoh_work.xml
sed -i 's/\">\[Dan/\">\[Dan/g'      enghenoh_work.xml
sed -i 's/\">\[Ef/\">\[Eph/g'       enghenoh_work.xml
sed -i 's/\">\[Est/\">\[Esth/g'     enghenoh_work.xml
sed -i 's/\">\[Ezk/\">\[Ezek/g'     enghenoh_work.xml
sed -i 's/\">\[Ezr/\">\[Ezra/g'     enghenoh_work.xml
sed -i 's/\">\[Flm/\">\[Phlm/g'     enghenoh_work.xml
sed -i 's/\">\[Flp/\">\[Phil/g'     enghenoh_work.xml
sed -i 's/\">\[Gal/\">\[Gal/g'      enghenoh_work.xml
sed -i 's/\">\[Hab/\">\[Hab/g'      enghenoh_work.xml
sed -i 's/\">\[Heb/\">\[Heb/g'      enghenoh_work.xml
sed -i 's/\">\[Iz/\">\[Isa/g'       enghenoh_work.xml
sed -i 's/\">\[Jak/\">\[Jas/g'      enghenoh_work.xml
sed -i 's/\">\[Jer/\">\[Jer/g'      enghenoh_work.xml
sed -i 's/\">\[Jl/\">\[Joel/g'      enghenoh_work.xml
sed -i 's/\">\[Jn/\">\[John/g'      enghenoh_work.xml
sed -i 's/\">\[Job/\">\[Job/g'      enghenoh_work.xml
sed -i 's/\">\[Jon/\">\[Jonah/g'    enghenoh_work.xml
sed -i 's/\">\[Joz/\">\[Josh/g'     enghenoh_work.xml
sed -i 's/\">\[Jud/\">\[Jude/g'     enghenoh_work.xml
sed -i 's/\">\[Kol/\">\[Col/g'      enghenoh_work.xml
sed -i 's/\">\[Lk/\">\[Luke/g'      enghenoh_work.xml
sed -i 's/\">\[Mal/\">\[Mal/g'      enghenoh_work.xml
sed -i 's/\">\[Mih/\">\[Mic/g'      enghenoh_work.xml
sed -i 's/\">\[Mr/\">\[Mark/g'      enghenoh_work.xml
sed -i 's/\">\[Mt/\">\[Matt/g'      enghenoh_work.xml
sed -i 's/\">\[Nah/\">\[Nah/g'      enghenoh_work.xml
sed -i 's/\">\[Neh/\">\[Neh/g'      enghenoh_work.xml
sed -i 's/\">\[Oz/\">\[Hos/g'       enghenoh_work.xml
sed -i 's/\">\[Prd/\">\[Eccl/g'     enghenoh_work.xml
sed -i 's/\">\[Prg/\">\[Prov/g'     enghenoh_work.xml
sed -i 's/\">\[Ps/\">\[Ps/g'        enghenoh_work.xml
sed -i 's/\">\[Raz/\">\[Rev/g'      enghenoh_work.xml
sed -i 's/\">\[Rim/\">\[Rom/g'      enghenoh_work.xml
sed -i 's/\">\[Rut/\">\[Ruth/g'     enghenoh_work.xml
sed -i 's/\">\[Sod/\">\[Judg/g'     enghenoh_work.xml
sed -i 's/\">\[Sof/\">\[Zeph/g'     enghenoh_work.xml
sed -i 's/\">\[Tit/\">\[Titus/g'    enghenoh_work.xml
sed -i 's/\">\[Vp/\">\[Song/g'      enghenoh_work.xml
sed -i 's/\">\[Zah/\">\[Zech/g'     enghenoh_work.xml
sed -i 's/\">\[Žal/\">\[Lam/g'      enghenoh_work.xml


# Pa se brez oglatih oklepajev
sed -i 's/\">1 Jn/\">1John/g'   enghenoh_work.xml
sed -i 's/\">1 Kor/\">1Cor/g'   enghenoh_work.xml
sed -i 's/\">1 Kr/\">1Kgs/g'    enghenoh_work.xml
sed -i 's/\">1 Krn/\">1Chr/g'   enghenoh_work.xml
sed -i 's/\">1 Mz/\">Gen/g'     enghenoh_work.xml
sed -i 's/\">1 Pt/\">1Pet/g'    enghenoh_work.xml
sed -i 's/\">1 Sam/\">1Sam/g'   enghenoh_work.xml
sed -i 's/\">1 Tes/\">1Thess/g' enghenoh_work.xml
sed -i 's/\">1 Tim/\">1Tim/g'   enghenoh_work.xml
sed -i 's/\">2 Jn/\">2John/g'   enghenoh_work.xml
sed -i 's/\">2 Kor/\">2Cor/g'   enghenoh_work.xml
sed -i 's/\">2 Kr/\">2Kgs/g'    enghenoh_work.xml
sed -i 's/\">2 Krn/\">2Chr/g'   enghenoh_work.xml
sed -i 's/\">2 Mz/\">Exod/g'    enghenoh_work.xml
sed -i 's/\">2 Pt/\">2Pet/g'    enghenoh_work.xml
sed -i 's/\">2 Sam/\">2Sam/g'   enghenoh_work.xml
sed -i 's/\">2 Tes/\">2Thess/g' enghenoh_work.xml
sed -i 's/\">2 Tim/\">2Tim/g'   enghenoh_work.xml
sed -i 's/\">3 Jn/\">3John/g'   enghenoh_work.xml
sed -i 's/\">3 Mz/\">Lev/g'     enghenoh_work.xml
sed -i 's/\">4 Mz/\">Num/g'     enghenoh_work.xml
sed -i 's/\">5 Mz/\">Deut/g'    enghenoh_work.xml
sed -i 's/\">Abd/\">Obad/g'     enghenoh_work.xml
sed -i 's/\">Ag/\">Hag/g'       enghenoh_work.xml
sed -i 's/\">Am/\">Amos/g'      enghenoh_work.xml
sed -i 's/\">Apd/\">Acts/g'     enghenoh_work.xml
sed -i 's/\">Dan/\">Dan/g'      enghenoh_work.xml
sed -i 's/\">Ef/\">Eph/g'       enghenoh_work.xml
sed -i 's/\">Est/\">Esth/g'     enghenoh_work.xml
sed -i 's/\">Ezk/\">Ezek/g'     enghenoh_work.xml
sed -i 's/\">Ezr/\">Ezra/g'     enghenoh_work.xml
sed -i 's/\">Flm/\">Phlm/g'     enghenoh_work.xml
sed -i 's/\">Flp/\">Phil/g'     enghenoh_work.xml
sed -i 's/\">Gal/\">Gal/g'      enghenoh_work.xml
sed -i 's/\">Hab/\">Hab/g'      enghenoh_work.xml
sed -i 's/\">Heb/\">Heb/g'      enghenoh_work.xml
sed -i 's/\">Iz/\">Isa/g'       enghenoh_work.xml
sed -i 's/\">Jak/\">Jas/g'      enghenoh_work.xml
sed -i 's/\">Jer/\">Jer/g'      enghenoh_work.xml
sed -i 's/\">Jl/\">Joel/g'      enghenoh_work.xml
sed -i 's/\">Jn/\">John/g'      enghenoh_work.xml
sed -i 's/\">Job/\">Job/g'      enghenoh_work.xml
sed -i 's/\">Jon/\">Jonah/g'    enghenoh_work.xml
sed -i 's/\">Joz/\">Josh/g'     enghenoh_work.xml
sed -i 's/\">Jud/\">Jude/g'     enghenoh_work.xml
sed -i 's/\">Kol/\">Col/g'      enghenoh_work.xml
sed -i 's/\">Lk/\">Luke/g'      enghenoh_work.xml
sed -i 's/\">Mal/\">Mal/g'      enghenoh_work.xml
sed -i 's/\">Mih/\">Mic/g'      enghenoh_work.xml
sed -i 's/\">Mr/\">Mark/g'      enghenoh_work.xml
sed -i 's/\">Mt/\">Matt/g'      enghenoh_work.xml
sed -i 's/\">Nah/\">Nah/g'      enghenoh_work.xml
sed -i 's/\">Neh/\">Neh/g'      enghenoh_work.xml
sed -i 's/\">Oz/\">Hos/g'       enghenoh_work.xml
sed -i 's/\">Prd/\">Eccl/g'     enghenoh_work.xml
sed -i 's/\">Prg/\">Prov/g'     enghenoh_work.xml
sed -i 's/\">Ps/\">Ps/g'        enghenoh_work.xml
sed -i 's/\">Raz/\">Rev/g'      enghenoh_work.xml
sed -i 's/\">Rim/\">Rom/g'      enghenoh_work.xml
sed -i 's/\">Rut/\">Ruth/g'     enghenoh_work.xml
sed -i 's/\">Sod/\">Judg/g'     enghenoh_work.xml
sed -i 's/\">Sof/\">Zeph/g'     enghenoh_work.xml
sed -i 's/\">Tit/\">Titus/g'    enghenoh_work.xml
sed -i 's/\">Vp/\">Song/g'      enghenoh_work.xml
sed -i 's/\">Zah/\">Zech/g'     enghenoh_work.xml
sed -i 's/\">Žal/\">Lam/g'      enghenoh_work.xml



# Pobrise prazne vrstice
sed -i "/^$/d"   enghenoh_work.xml

mkdir mods.d                                  > /dev/null 2>&1
mkdir modules                                 > /dev/null 2>&1
mkdir modules/genbook                         > /dev/null 2>&1
mkdir modules/genbook/rawgenbook              > /dev/null 2>&1
mkdir modules/genbook/rawgenbook/enghenoh     > /dev/null 2>&1

echo  "   Preveri XML"
/usr/bin/xmllint --noout --schema http://www.crosswire.org/~dmsmith/osis/osisCore.2.1.1-cw-latest.xsd enghenoh_work.xml

sleep 2  # Waits 2 seconds.

# Konvertireanje v SWORD modul
/usr/bin/xml2gbs -fO enghenoh_work.xml enghenoh  > /dev/null 2>&1
mv enghenoh.bdt modules/genbook/rawgenbook/enghenoh/
mv enghenoh.dat modules/genbook/rawgenbook/enghenoh/
mv enghenoh.idx modules/genbook/rawgenbook/enghenoh/
cp -u enghenoh.conf mods.d/

# Preverimo ali je sed pravilno naredil
cat enghenoh_work.xml |grep opomba\>
cat enghenoh_work.xml |grep "SLO "

# Module prekopira da jih sword lahko vidi
cp -r mods.d/ /usr/share/sword/
cp -r modules/ /usr/share/sword/


# Izvoz iz modula - povsod odstraniti tiste $$$
# mod2imp SloHenoh -r LATEX >SloHenoh.tex
# mod2imp SloHenoh -r RTF >SloHenoh.rtf
# mod2imp SloHenoh -r HTMLHREF >SloHenoh.html  
echo "   Izvoz v txt"
mod2imp SloHenoh -s >SloHenoh.txt
mod2imp EngHenoh -s >EngHenoh.txt

sed -i 's/  * /\n* /g'   SloHenoh.txt
sed -i 's/  * /\n* /g'   EngHenoh.txt


#=======================================================================================
#=======================================================================================
#                      OSIS ->  USFM  konverzija
#                      SLO in ENG  konfiguracija
#=======================================================================================
#=======================================================================================

#==================== Anglesko verzijo ali Slovensko ========================
echo " "
echo "   Angleško verzijo ali Slovensko?"
echo " "
PS1='   Izberi: '
options_ver=("Slo" "Eng" "Izhod")
select opt_lang in "${options_ver[@]}"
do
      case $opt_lang in
          "Slo")
              echo " "
              echo "   Slovensko."
              echo " "
                # ==================== Naredi potrebne mape =============================================
                mkdir /home/pc/Dokumenti/GitHub/SloKJV/PTXprint/osis2usfm/SloKJV/release/slohenoh   2>/dev/null
                # =================== Spremenljivke =====================================================
                input=/home/pc/Dokumenti/slohenoh/slohenoh.xml
                output=/home/pc/Dokumenti/osis2usfm/SloKJV/release/slohenoh/19-PSA.usfm
                # ======= Kopira xml datoteko na lokacijo kjer jo bo spreminjal ========================
                cp /home/pc/Dokumenti/slohenoh/slohenoh_work.xml $input
              break
             ;;
          "Eng")
              echo " "
              echo "   Angleško."
              echo " "
                # ==================== Naredi potrebne mape =============================================
                mkdir /home/pc/Dokumenti/GitHub/SloKJV/PTXprint/osis2usfm/SloKJV/release/enoch   2>/dev/null
                # =================== Spremenljivke =====================================================
                input=/home/pc/Dokumenti/slohenoh/enghenoh.xml
                output=/home/pc/Dokumenti/osis2usfm/SloKJV/release/enoch/19-PSA.usfm
                # ======= Kopira xml datoteko na lokacijo kjer jo bo spreminjal ========================
                cp /home/pc/Dokumenti/slohenoh/enghenoh_work.xml $input
              break
              ;;
          "Izhod")
              echo " "
              echo "   Izbral si $REPLY kar je $opt_ver"
              echo " "
              exit
             ;;
          *) echo "   Napacna izbira $REPLY";;
      esac
done
#===================================================================


# ============== Pretvori OSIS datoteko v USX obliko ===================================
# ======= REFERENCE ===============
# Najprej samo zmanjsa reference -> ;XYX
sed -i "s|</reference>; <reference osisRef=|;XYX|g"            $input

# tukaj glede druge po vrsti in naslednje reference v enem note zapisu in spremeni vmesne dele v podpicja
#         ;XYX"Acts.17.24">   zamenja ->  ;
sed -i "s|;XYX\"[^\"]*\">|; |g"                                $input

#   <reference osisRef="Ps.33.6">   zamenjam z nic to je prva opomba angleski del da ostane samo slovenski del
sed -i "s|<reference osisRef=\"[^\"]*\">|; |g"                 $input

# Odstrani se  </reference></note> in zamenja ->  \x*
sed -i "s|</reference></note>|\x5cx*|g"                       $input

# Zamenja <note type="crossReference">;   ->   \x - \xo:  PPP
sed -i "s|<note type=\"crossReference\">;|\x5cx + \x5cxo \x5creference : \x5cxt |g" $input

# Tu zgoraj sem odstranil  + \x5cfxt

cat $input |grep "<verse osisID=\"Deut.33.1\""
cat $input |grep "<reference"
cat $input |grep "reference>"
# head -30 $input


# ======= OPOMBE ===============
#    --==    <note type=\"x-footnote\">  \</note> "
#    --==   \f opomba \f*"
sed -i "s|<note type=\"x-footnote\">|\x5cf + \x5cfr \x5creference : \x5cft |g"   $input
sed -i "s|</note>|\x5cf*|g"                                                      $input
cat $input |grep "<note type=\"x-footnote\">"
cat $input |grep "<note>"
cat $input |grep "</note>"
#==============================


# ======= DODANE BESEDE ITALIC ===============
#    --==    <transChange type=\"added\">je bila</transChange>     "
#    --==   \add was\add*     "
sed -i "s|<transChange type=\"added\">|\x5cadd |g"                              $input
sed -i "s|</transChange>|\x5cadd*|g"                                            $input
cat $input |grep "transChange"
# =======================================================


#============ ZACETEK ================================================
#         Pobrise prvih 28 vrstic
sed -i "1,28d"                                                                  $input
      case $opt_lang in
          "Slo")
                 #  Add begining - Slovensko.
                 #  Namesto   \id ENO    dam   \id PSA   da ga prepricam da je to biblija drugace noce delati
                 sed -i '1i \\\id PSA'                             $input
                 sed -i '2i \\\h Henoh'                            $input
                 sed -i '3i \\\h1 HENOHOVA KNJIGA'                 $input
                 sed -i '4i \\\toc1 Henohova knjiga'               $input
                 sed -i '5i \\\toc2 Hen'                           $input
                 sed -i '6i \\\mt2 H.R. Charles'                   $input
                 sed -i '7i \\\mt1 HENOHOVA KNJIGA'                $input
                 sed -i '8i \\\pb'                                 $input
#              break
             ;;
          "Eng")
                 #  Add begining - Angleško.
                 sed -i '1i \\\id PSA'                             $input
                 sed -i '2i \\\h Enoch'                            $input
                 sed -i '3i \\\h1 The Book of Enoch'               $input
                 sed -i '4i \\\toc1 The Book of Enoch'             $input
                 sed -i '5i \\\toc2 ENO'                           $input
                 sed -i '6i \\\mt2 H.R. Charles'                   $input
                 sed -i '7i \\\mt1 THE BOOK OF ENOCH'              $input
                 sed -i '8i \\\pb'                                 $input
#              break
              ;;
          "Izhod")
              echo " "
              echo "   Izbral si $REPLY kar je $opt_ver"
              echo " "
              exit
             ;;
          *) echo "   Napacna izbira $REPLY";;
      esac
#=====================================================================


# ===================== DIV TYPE BOOK ================================
#           <div type=\"book\" osisID=\"Gen\">  ->   <div type=\"book\">
echo -E " "
sed -i "s|<div type=\"book\" osisID=\"\([^.]*\)\">     |<div type=\"book\">|g"  $input
cat $input |grep "book\"osisID="
#=============================================================


# ===================== ZACETEK ODSTRANI ================================
#<?xml version=\"1.0\" encoding=\"UTF-8\" ?>
#<osis xmlns=\"http://www.bibletechnologies.net/2003/OSIS/namespace\"
#       xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"
#       xsi:schemaLocation=\"http://www.bibletechnologies.net/2003/OSIS/namespace http://www.crosswire.org/~dmsmith/osis/osisCore.2.1.1-cw-latest.xsd\">
#            ->    <osis>
#
sed -i "s|<?xml version=\"1.0\" encoding=\"UTF-8\"?>||g"                                       $input
sed -i "s|<osis xmlns=\"http://www.bibletechnologies.net/2003/OSIS/namespace\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://www.bibletechnologies.net/2003/OSIS/ce http://www.crosswire.org/~dmsmith/osis/osisCore.2.1.1-cw-latest.xsd\">|<osis>|g"       $input

#sed -i "s|<osis> xmlns=\"http://www.bibletechnologies.net/2003/OSIS/namespace\"|<osis>|g"       $input
#sed -i "s|      xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"||g"                    $input
#sed -i "s|      xsi:schemaLocation=\"http://www.bibletechnologies.net/2003/OSIS/namespace http://www.crosswire.org/~dmsmith/osis/osisCore.2.1.1-cw-latest.xsd\">||g"                                        $input
#
#<osisText osisIDWork=\"SloKJV\" osisRefWork=\"Bible\" xml:lang=\"sl\">
#            ->    <osisText>
sed -i "s|<osisText osisRefWork=\"GenBook\" canonical=\"true\" osisIDWork=\"Slohenoh\" xml:lang=\"sl\">|<osisText>|g" $input
cat $input |grep "xmlns"
#=============================================================


#=================== ODSTRANI PRESLEDKE ==================================
# Odstrani presledke, enega ali vec, na zacetku vrstic
sed -i "s/^[ ]*//g"                                      $input
# Odstrani presledke, enega ali vec, na koncu vrstic
sed -i 's/ *$//'                                         $input
#=========================================================================


# ================== <\/div> potegne  ================================
#  Potegne gor vrstico  
#   </div>
#   <div type="chapter" osisID="Poglavje 2">
sed -i ':a;N;$!ba;s|<\/div>\n<div type=|<\/div><div type=|g'   $input
# cat $input |grep "<div type=\"chapter\""
# ============================================================================


# ===================== REMOVE CHAPTER OSIS ID  ================================
#      Popraviti zaradi python skripta
#    <chapter osisID=\"Gen.01\" chapterTitle=\"1. Poglavje\">   ->   <chapter>
echo -E " "
      case $opt_lang in
          "Slo")
                #   REMOVE CHAPTER OSIS ID - Slovensko.
                #============= Major secton   -> \ms  ===============================
                #         </div>
                #         </div><div type="majorSection" osisID="Razdelek IV">
                #              ->    \ms
                sed -i  "s/<\/div><div type=\"majorSection\" osisID=\"\([^.]*\)\">/\\\ms \1/g" $input
                #          <div type="majorSection"   osisID="Razdelek I">
                sed -i  "s/<div type=\"majorSection\" osisID=\"\([^.]*\)\">/\\\ms \1/g"        $input
                #         Pobrise se vse preostale </div>
                sed -i  "s/<\/div>//g"                                                         $input
                #       Pobrise vse     <p><hi type="bold">Razdelek  ker se sicer 2x pojavi
                sed -i  "s/<p><hi type=\"bold\">Razdelek [A-Z]*<\/hi><\/p>//g"                 $input

                #============== Chapter spremeni v nic =============
                #         <div type= "chapter " osisID= "Poglavje 1">   pobrise
                sed -i "s/<\/div><div type=\"chapter\" osisID=\"Poglavje \([0-9]*\)\">//g"     $input
                sed -i "s/<div type=\"chapter\" osisID=\"Poglavje \([0-9]*\)\">//g"            $input
                sed -i "s/<div type=\"chapter\" osisID=\"Poglavje 91a\">//g"                   $input
                #====================================================================
#              break
             ;;
          "Eng")
                #   REMOVE CHAPTER OSIS ID - Angleško.
                #============= Major secton   -> \ms  ===============================
                #         </div>
                #         </div><div type="majorSection" osisID="Section II">
                #              ->    \ms
                sed -i  "s/<\/div><div type=\"majorSection\" osisID=\"\([^.]*\)\">/\\\ms \1/g" $input
                #          <div type="majorSection"   osisID="Section I">
                sed -i  "s/<div type=\"majorSection\" osisID=\"\([^.]*\)\">/\\\ms \1/g"        $input
                #         Pobrise se vse preostale </div>
                sed -i  "s/<\/div>//g"                                                         $input
                #       Pobrise vse     p><hi type="bold">Section I.</hi></p  ker se sicer 2x pojavi
                sed -i  "s/<p><hi type=\"bold\">Section [A-Z]*\.<\/hi><\/p>//g"                  $input
                #============== Chapter spremeni v nic =============
                #         <div type="chapter" osisID="Chapter 37">      delete
                sed -i "s/<\/div><div type=\"chapter\" osisID=\"Chapter \([0-9]*\)\">//g"     $input
                sed -i "s/<div type=\"chapter\" osisID=\"Chapter \([0-9]*\)\">//g"            $input
                sed -i "s/<div type=\"chapter\" osisID=\"Chapter 91a\">//g"                   $input
                #====================================================================
#              break
              ;;
          "Izhod")
              echo " "
              echo "   Izbral si $REPLY kar je $opt_ver"
              echo " "
              exit
             ;;
          *) echo "   Napacna izbira $REPLY";;
      esac
   cat $input |grep "majorSection"
   #cat $input |grep "Razdelek"
   cat $input |grep "<div type=\"chapter\""
#=============================================================


#===========  Vrstice  <row><cell><hi type="super">   ->   \v ===================
#       <hi type="super">1</hi>
sed -i 's/<row><cell><hi type=\"super\">\([0-9]*\)<\/hi>/\n\\q1\n\\v \1/'          $input
sed -i 's/<row><cell><hi type=\"super\">\([0-9]*[a-z]*\)<\/hi>/\n\\q1\n\\v \1/'    $input
cat $input |grep "cell><hi ty"
#================================================================================


#===========  Vrstice   <hi type="super">   ->   \v ===================
#       <hi type="super">1</hi>
sed -i 's/<hi type=\"super\">\([0-9]*\)<\/hi>/\\v \1/'          $input
sed -i 's/<hi type=\"super\">\([0-9]*[a-z]*\)<\/hi>/\\v \1/'    $input
cat $input |grep "type=\"super"
#=====================================================================


#============== Tabele  spremeni v zamike ===========================
#           <row><cell></cell></row> naredi presledek da ni vec zamikov
sed -i 's/<row><cell><\/cell><\/row>/\\p\n/'                   $input
#           <row><cell>\v   spremeni  v 
#                 \v
sed -i 's/<row><cell>\\v/\\v/'                                 $input
#           1x <row><cell> spremeni v zamik  \q1
sed -i 's/<row><cell>/\\q1/'                                   $input
#           <table>   pobrise
sed -i 's/<\/table>//'                                         $input
#           </table>  pobrise
sed -i 's/<table>//'                                           $input
#           </cell></row>  pobrise
sed -i 's/<\/cell><\/row>//'                                   $input
#====================================================================


#========== Naslovi poglavij  ->    \ms1    ==========================
#      Zamenja  </hi></p>  z novo vrstico in  \p
sed -i 's/<\/hi><\/p>/\n\\\p/'                                 $input
#      <p><hi type="bold">  ->   \ms1
sed -i 's/<p><hi type=\"bold\">/\\\ms1 /'                      $input
sed -i 's/<hi type=\"bold\">/\\\ms1 /'                         $input
#      SPremeni <p> -> \ms1   in  odstrani <p>
sed -i 's/<p>/\\\ms1 /'                                        $input
sed -i 's/<\/p>//'                                             $input
#====================================================================


#===============  POGLAVJE ==========================================
#        Kjer je <title>Poglavje 4</title>   brez opombe pobriem
#   \c 111
#   \s1
#   \p
      case $opt_lang in
          "Slo")
                #   Poglavje - Slovensko.
                sed -i "s/<title>Poglavje \([0-9]*[a-z]*\)<\/title>/\\\c \1\n\\\s1\n\\\p/g" $input
                #        Vprasljivo ??   <title> -> \mt4
                sed -i "s/<title>/\\\mt4 /g"                                   $input
                #        PŠobrise vse konce </title>
                sed -i "s/<\/title>//g"                                        $input
#             break
             ;;
          "Eng")
                #   Chapter - Angleško.
                #         <title>Chapter 1</title>
                sed -i "s/<title>Chapter \([0-9]*[a-z]*\)<\/title>/\\\c \1\n\\\s1\n\\\p/g" $input
                #        Vprasljivo ??   <title> -> \mt4
                sed -i "s/<title>/\\\mt4 /g"                                   $input
                #        PŠobrise vse konce </title>
                sed -i "s/<\/title>//g"                                        $input
#              break
              ;;
          "Izhod")
              echo "       Izbral si $REPLY kar je $opt_ver"
              exit
             ;;
          *) echo "   Napacna izbira $REPLY";;
      esac
#====================================================================


#========= Pobrise konec ============================================
#      </osisText>
#      </osis>
sed -i  "s/<\/osisText>//g"                              $input
sed -i  "s/<\/osis>//g"                                  $input
sed -i "s|<\/hi>|\\\bdit*|g"                                                    $input
#====================================================================


#====================================================================
#      Zamenja \p      ker so preveliki razmiki, recimo  Poglavje 1
#              \c 1
sed -i ':a;N;$!ba;s|\\p\n\\c|\n\\c|g'                     $input
#cat $input |grep -2 " 102"
#====================================================================


#====================================================================
#      Zamenja \b      ker so preveliki razmiki, recimo  Poglavje 102
#              \c 1
sed -i ':a;N;$!ba;s|\\b\n\\c|\n\\c|g'                     $input
#cat $input |grep -2 " 102"
#====================================================================


# ================== Na koncu doda eno vrstico \pb ==================
# Doda zato da se 108 poglavje lepo razdeli na tri strani
sed -i -e '$a\'$'\n''\\pb'                                $input
# ================== Odstrani prazne vrstice ========================


# ================== Odstrani prazne vrstice ========================
sed -i -e "/^$/d"                                         $input
# ===================================================================


#=================== Pripravi datoteke za PTXprint ==================
# Pobrise vse morebitne ostale fajle v mapi
rm /home/pc/Dokumenti/osis2usfm/SloKJV/release/slohenoh/*.usfm  > /dev/null 2>&1
rm /home/pc/Dokumenti/osis2usfm/SloKJV/release/enoch/*.usfm     > /dev/null 2>&1
# Prekopira fajl in ga ponesreceno poimenuje namesto B5-ENO.usfm  v   19-PSA.usfm
cp $input $output
#head -150 $input >$output
#====================================================================


#================ Požene PTXprint ===================================
# Gre v pravo mapo. Nisem preprica da je to potrebno
cd /home/pc/Dokumenti/osis2usfm/

      case $opt_lang in
          "Slo")
              echo " "
              echo "   Požene PTXprint - Slovensko."
              echo " "
                ptxprint -c   /home/pc/Dokumenti/osis2usfm/SloKJV/release  slohenoh
              break
             ;;
          "Eng")
              echo " "
              echo "   Požene PTXprint - Angleško."
              echo " "
                ptxprint -c   /home/pc/Dokumenti/osis2usfm/SloKJV/release  enoch
              break
              ;;
          "Izhod")
              echo " "
              echo "   Izbral si $REPLY kar je $opt_ver"
              echo " "
              exit
             ;;
          *) echo "   Napacna izbira $REPLY";;
      esac
#====================================================================

#==================== Pozene GITHUB Desktop? ========================
echo " "
echo "   Pozene GITHUB Desktop?"
echo " "
PS5='   Izberi: '
options_ver=("Ne" "Pozene" "Izhod")
select opt_ver in "${options_ver[@]}"
do
      case $opt_ver in
          "Ne")
              echo " "
              echo "   Pa drugic sinhronizacija z Githubom."
              echo " "
              break
             ;;
          "Pozene")
              echo " "
              echo "   Izbral si Github."
              echo " "
              echo "      Kopira v Github mapo..."
              echo " "
                # Slo
                cp /home/pc/Dokumenti/slohenoh/slohenoh_work.xml $Github/slohenoh.osis.xml
                cp /home/pc/Dokumenti/slohenoh/slohenoh.conf     $Github/slohenoh.conf
                cp /home/pc/Dokumenti/slohenoh/slohenoh.xml      $Github/slohenoh.usfm
                cp /home/pc/Dokumenti/osis2usfm/SloKJV/release/slohenoh/local/ptxprint/slohenoh_Default_PSA_ptxp.pdf  $Github/SloHenoh.pdf
                # Eng
                cp /home/pc/Dokumenti/slohenoh/enghenoh_work.xml $Github/enoch/enoch.osis.xml
                cp /home/pc/Dokumenti/slohenoh/enghenoh.conf     $Github/enoch/enoch.conf
                cp /home/pc/Dokumenti/slohenoh/enghenoh.xml      $Github/enoch/enoch.usfm
                cp /home/pc/Dokumenti/osis2usfm/SloKJV/release/enoch/local/ptxprint/enoch_Default_PSA_ptxp.pdf        $Github/enoch/Enoch.pdf
                # Skripta in izvirnik
                cp /home/pc/Dokumenti/slohenoh/run_SloHenoh      $Github/scripts/run_SloHenoh
                cp /home/pc/Dokumenti/slohenoh/sloenghenoh.xml   $Github/scripts/sloenghenoh.xml
              echo " "
              echo "     Sinhronizacija z Githubom ..."
              echo " "
              echo "   --==  Pozene /usr/bin/github-desktop ==--"
              echo " "
              /usr/bin/github-desktop
              break
              ;;
          "Izhod")
              echo " "
              echo "   Izbral si $REPLY kar je $opt_ver"
              echo " "
              exit
             ;;
          *) echo "   Napacna izbira $REPLY";;
     esac
done
#===================================================================
